language: scala
scala: 
  - 2.11.2
jdk:
  - oraclejdk8
script:
  - "cd $TRAVIS_BUILD_DIR/code"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"
notifications:
  email: false