language: scala
env:
  - PLAY_VERSION=2.4.6 # Latest
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
script: play-${PLAY_VERSION}/play test